blueprint:
  name: Cancel Light Sunrise on Manual Change
  description: >
    Cancels a running Light Sunrise script when a manual change is detected.
    Compares observed light changes against the script's stored targets
    (in input_number helpers). If brightness or kelvin is moving AWAY from
    the target, it's a manual change and the script is cancelled. If moving
    toward the target, it's the script's transition — ignored.
    Requires helpers: input_number.sunrise_target_brightness and
    input_number.sunrise_target_kelvin.
  domain: automation
  input:
    target_light:
      name: 💡 Target Light
      description: The light to monitor for manual changes.
      selector:
        entity:
          filter:
            domain: light

    sunrise_script:
      name: 📄 Sunrise Script
      description: The Light Sunrise script entity to cancel.
      default: script.light_sunrise
      selector:
        entity:
          filter:
            domain: script

variables:
  sunrise_script_entity: !input sunrise_script
  bri_helper: input_number.sunrise_target_brightness
  kelvin_helper: input_number.sunrise_target_kelvin

triggers:
  - entity_id: !input target_light
    trigger: state

conditions:
  # Script must be running
  - condition: template
    value_template: "{{ states(sunrise_script_entity) == 'on' }}"

  # Check if the observed change does NOT match the script's trajectory.
  # The script stores its current target brightness (%) and kelvin in helpers.
  # If the light is moving AWAY from either target, it's a manual change.
  - condition: template
    value_template: >
      {% set target_bri = states(bri_helper) | float(0) * 2.55 %}
      {% set target_k = states(kelvin_helper) | float(0) %}
      {% set old_bri = trigger.from_state.attributes.brightness | float(0) %}
      {% set new_bri = trigger.to_state.attributes.brightness | float(0) %}
      {% set old_k = trigger.from_state.attributes.color_temp_kelvin | float(0) %}
      {% set new_k = trigger.to_state.attributes.color_temp_kelvin | float(0) %}
      {% set bri_was = (old_bri - target_bri) | abs %}
      {% set bri_now = (new_bri - target_bri) | abs %}
      {% set k_was = (old_k - target_k) | abs %}
      {% set k_now = (new_k - target_k) | abs %}
      {% set bri_off_track = bri_now > bri_was + 5 %}
      {% set k_off_track = k_now > k_was + 30 %}
      {{ trigger.to_state.state == 'off' or bri_off_track or k_off_track }}

actions:
  - target:
      entity_id: "{{ sunrise_script_entity }}"
    action: script.turn_off

mode: single
