blueprint:
  name: Light Sunrise
  description: >
    Turns on a light at a starting brightness and color temperature, then
    transitions to an end brightness and color temperature over a set duration
    using a single light.turn_on command with a long transition.
  domain: automation
  input:
    alarm_start_time:
      name: 🕒 Start Time
      description: Datetime helper or timestamp sensor for the alarm start.
      selector:
        entity:
          filter:
            - domain: input_datetime
            - domain: sensor
              device_class: timestamp
          multiple: false

    offset_from_start_time:
      name: 🏁 Offset
      description: >-
        Offset from start time, e.g. "-00:15:00" to start 15 minutes early.
      default: "-00:00:00"
      selector:
        text:

    conditions:
      name: ✅ Conditions
      description: Additional conditions that must pass for the alarm to run.
      default: []
      selector:
        condition:

    target_light:
      name: 💡 Target Light
      description: A single light or group.
      selector:
        entity:
          filter:
            domain: light

    start_brightness:
      name: ⭐ Start Brightness (%)
      default: 1
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider

    start_kelvin:
      name: ☀️ Start Kelvin
      description: Starting color temperature (warm).
      default: 2500
      selector:
        color_temp:
          unit: kelvin

    end_brightness:
      name: 🌟 End Brightness (%)
      default: 100
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider

    end_kelvin:
      name: 🌑 End Kelvin
      description: Final color temperature (cool).
      default: 6500
      selector:
        color_temp:
          unit: kelvin

    duration:
      name: ⏰ Duration (min)
      description: How long the transition takes in minutes.
      default: 15
      selector:
        number:
          min: 1
          max: 60
          step: 1
          mode: slider

    additional_actions:
      name: 🎮 Additional Actions
      description: Optional actions to run when the automation triggers (before the light turns on).
      default: []
      selector:
        action: {}


trigger:
  - trigger: time
    at:
      entity_id: !input alarm_start_time
      offset: !input offset_from_start_time

condition:
  condition: and
  conditions: !input conditions

variables:
  target_light: !input target_light
  duration: !input duration
  start_brightness: !input start_brightness
  start_kelvin: !input start_kelvin
  end_brightness: !input end_brightness
  end_kelvin: !input end_kelvin

action:
  # Optional additional actions
  - choose:
      - conditions: []
        sequence: !input additional_actions

  # Turn on at starting values
  - service: light.turn_on
    target:
      entity_id: !input target_light
    data:
      brightness_pct: "{{ start_brightness }}"
      color_temp_kelvin: "{{ start_kelvin }}"

  - delay:
      seconds: 2

  # Transition to end values
  - service: light.turn_on
    target:
      entity_id: !input target_light
    data:
      brightness_pct: "{{ end_brightness }}"
      color_temp_kelvin: "{{ end_kelvin }}"
      transition: "{{ duration | int * 60 }}"


mode: parallel
