blueprint:
  name: Light Sunrise
  description: >
    Turns on a light at a starting brightness and color temperature, then
    transitions to an end brightness and color temperature over a set duration
    using a single light.turn_on command with a long transition.
  domain: automation
  input:
    alarm_start_time:
      name: ðŸ•’ Start Time
      description: Datetime helper or timestamp sensor for the alarm start.
      selector:
        entity:
          filter:
            - domain: input_datetime
            - domain: sensor
              device_class: timestamp
          multiple: false

    offset_from_start_time:
      name: ðŸ Offset
      description: >-
        Offset from start time, e.g. "-00:15:00" to start 15 minutes early.
      default: "-00:00:00"
      selector:
        text:

    conditions:
      name: âœ… Conditions
      description: Additional conditions that must pass for the alarm to run.
      default: []
      selector:
        condition:

    target_light:
      name: ðŸ’¡ Target Light
      description: A single light or group.
      selector:
        entity:
          filter:
            domain: light

    start_brightness:
      name: â­ Start Brightness (%)
      default: 1
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider

    start_kelvin:
      name: â˜€ï¸ Start Kelvin
      description: Starting color temperature (warm).
      default: 2500
      selector:
        color_temp:
          unit: kelvin

    end_brightness:
      name: ðŸŒŸ End Brightness (%)
      default: 100
      selector:
        number:
          min: 1
          max: 100
          step: 1
          mode: slider

    end_kelvin:
      name: ðŸŒ‘ End Kelvin
      description: Final color temperature (cool).
      default: 6500
      selector:
        color_temp:
          unit: kelvin

    duration:
      name: â° Duration (min)
      description: How long the transition takes in minutes.
      default: 15
      selector:
        number:
          min: 1
          max: 60
          step: 1
          mode: slider

    light_timeout:
      name: â±ï¸ Light Timeout (min)
      description: >-
        Turn off the light this many minutes after the transition finishes.
        Set to 0 to leave it on.
      default: 0
      selector:
        number:
          min: 0
          max: 60
          step: 1
          mode: slider

trigger:
  - trigger: time
    at:
      entity_id: !input alarm_start_time
      offset: !input offset_from_start_time

condition:
  condition: and
  conditions: !input conditions

variables:
  target_light: !input target_light
  duration: !input duration
  light_timeout: !input light_timeout

action:
  # Turn on at starting values
  - action: light.turn_on
    target:
      entity_id: !input target_light
    data:
      brightness_pct: !input start_brightness
      color_temp_kelvin: !input start_kelvin

  - delay:
      seconds: 2

  # Transition to end values
  - action: light.turn_on
    target:
      entity_id: !input target_light
    data:
      brightness_pct: !input end_brightness
      color_temp_kelvin: !input end_kelvin
      transition: "{{ duration | int * 60 }}"

  # Wait for the transition to finish
  - delay:
      minutes: "{{ duration }}"

  # Optional timeout
  - if:
      - condition: template
        value_template: "{{ light_timeout | int > 0 and not is_state(target_light, 'off') }}"
    then:
      - delay:
          minutes: "{{ light_timeout }}"
      - action: light.turn_off
        target:
          entity_id: !input target_light

mode: parallel
